### ISSUE TITLE
PDB not populating 10.14 line (and 10.15 is missing)

### ISSUE THREAD

**Issue by nieder** [fink/pdb#2]
The PDB is updating versions but is not populating the data for 10.14 and missing higher dists.

See http://pdb.finkproject.org/pdb/package.php/openblas as an example. 0.3.8 was recently pushed for 10.9+, but is not showing up for 10.14, 10.14.5, and 10.15.

Do we need to replicate 81c9f52 and fink/website@4d59c2c for 10.15?

@TheSin-

**Comment by dmacks** [comment]
Not just "not populating the data", but doesn't even have a row for 10.15.

**Comment by TheSin-** [comment]
it just needs to be updated in the website and pdb files, the pub server will auto update from git.

I'll look it at it as soon as I have time but I can't promise when that will be.

10.14 surprises me honestly

10.14.5 and 10.15 doesn't as it was never added.

**Comment by nieder** [comment]
I can do some of it tonight if it's just a matter of replicating those 2 commits so that the table is at least expanded to 10.15 (even if empty). I'll also poke around to see if some other file needs to be tickled in order to populate 10.14.

**Comment by TheSin-** [comment]
I won't add the bindists for them as I haven't had time to start a builder, I plan to make a soccer image for the builder as some point.

**Comment by TheSin-** [comment]
just made some commits to the pdb and to the web repo to add 10.14.5 and 10.15

looks like lots of the faqs need to be updated to include 10.14.5 and 10.15 as well though, like the installer script ref and such.

**Comment by TheSin-** [comment]
the 10.14.5 and 10.15 rows show up on pdb now.

Just need to wait for pdb to finish a population run now.

**Comment by TheSin-** [comment]
```
Argument "" isn't numeric in sprintf at ./create-finkdb.pl line 657.
```

**Comment by TheSin-** [comment]
okay I think I found the issue, some parts haven't been converted from cvs so I needed to manually copy in the dist dir into the work dir, it'll run again in a couple hour I think and should work this time I hope

**Comment by TheSin-** [comment]
it's populated now, thanks for the report!

**Comment by nieder** [comment]
Thanks for the fix!
